ignored = ["k8s.io/client-go/pkg/api/v1"]

# See: https://github.com/golang/dep/issues/1799
[[override]]
  name = "gopkg.in/fsnotify.v1"
  source = "https://github.com/fsnotify/fsnotify.git"

# glog -> zap
[[override]]
  revision = "ad18aa91a01e5a7a4d312d16528a181979a23c62"
  name = "github.com/golang/glog"
  source = "github.com/prydie/glog"

[[constraint]]
  name = "github.com/onsi/ginkgo"
  version = "1.4.0"

[[constraint]]
  name = "github.com/onsi/gomega"
  version = "1.3.0"

[[constraint]]
 name = "github.com/kubernetes-incubator/external-storage"
 version = "4.0.0"

[[override]]
 name = "gopkg.in/gcfg.v1"

[[constraint]]
 name = "k8s.io/apimachinery"
 version = "kubernetes-1.11.1"

[[constraint]]
 name = "k8s.io/client-go"
 version = "kubernetes-1.11.1"

[[constraint]]
 name = "k8s.io/kubernetes"
 version = "1.11.1"

[[constraint]]
 version = "v2.6.0"
 name = "github.com/oracle/oci-go-sdk"

[[override]]
name = "github.com/docker/distribution"
revision = "f0cc927784781fa395c06317c58dea2841ece3a9" # Lock in to version 2.6.3 when it is released

[[override]]
 name = "k8s.io/api"
 version = "kubernetes-1.11.1"
