kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: run-oracle-provisioner
subjects:
  - kind: ServiceAccount
    name: oci-provisioner
    namespace: kube-system 
roleRef:
  kind: ClusterRole
  name: oci-provisioner-runner
  apiGroup: rbac.authorization.k8s.io
