kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: demooci
spec:
  storageClassName: "ffsw"
  selector:
    matchLabels:
      oci-availability-domain: "PHX-AD-1"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
