kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: demooci
spec:
  storageClassName: "oci"
  selector: 
    matchLabels:
      oci-availability-domain: "PHX-AD-3"
      oci-compartment: "bristol-cloud"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
