kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: oci-demo-block-storage-pvc
spec:
  storageClassName: "oci-block"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
